name: pullreq-ci
on:
  push:
    branches:
      - "main"
  pull_request:
jobs:
  pullreq-ci:
    name: golang-unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19'
      - uses: actions/checkout@v3
      - name: Run tests with coverage report output
        run: go test ./... -coverprofile=coverage.out
      - name: create report
        uses: k1LoW/octocov-action@v0
      - name: Notify slack when job failed
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "job_id": "${{ github.job }}",
              "author": "${{ github.event.sender.login }}",
              "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "repo_name": "${{ github.event.repository.full_name }}",
              "status": "${{ job.status }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WORKFLOW_WEBHOOK_URL }}